version: '3'
services:
  server:
    build: ./server
    container_name: server_c
    ports:
      - "1313:1313"
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client_c
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true